# -*- coding: utf-8 -*-
"""Bai2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vul0HFw8AHTHA3a5l_foYwbwAhdmzv1Z

Vòng lặp While:
"""

print("Giải phương trình bậc nhất ax+b=0")
n=int(input("Nhập n="))
while n>0:
    a=float(input("Nhập a="))
    b=float(input("Nhập b="))
    if a==0 and b==0:
        print("Vô số nghiệm")
    if a==0 and b!=0:
        print("Vô nghiệm")
    if a!=0 and b!=0:
        print("x=",-b/a)
    n-=1
print("Kết thúc chương trình")

"""Vòng lặp For:"""

print("Giải phương trình bậc nhất ax+b=0")
n=int(input("Nhập n="))
for i in range(n):
    a=float(input("Nhập a="))
    b=float(input("Nhập b="))
    if a==0 and b==0:
        print("Vô số nghiệm")
    if a==0 and b!=0:
        print("Vô nghiệm")
    if a!=0 and b!=0:
        print("x=",-b/a)
print("Kết thúc chương trình")